[files]
extend-exclude = [
  # these misspellings are intentional, so that they get automatically fixed:
  "config/nvim/plugin/autofix.vim",
  "config/nvim/spell/en.utf-8.add",

  # these are 3rd-party code, don't try to fix them
  "zsh/plugins/zsh-completions/",
  "zsh/plugins/bench/",
  "zsh/plugins/fast-syntax-highlighting/",
  "zsh/plugins/zsh-history-substring-search/",
  "zsh/plugins/autoswitch-virtualenv",

  # this has a bunch of junk in it, don't care. (also, 3rd-party)
  "config/kitty/glyphnames.json",
]

[default.extend-words]
# iTerm is a program name
iterm = "iterm"
