---@type LazySpec
return {
  { import = 'me.plugins.langs.ansible' },
  { import = 'me.plugins.langs.c' },
  { import = 'me.plugins.langs.crystal' },
  { import = 'me.plugins.langs.css' },
  { import = 'me.plugins.langs.docker' },
  { import = 'me.plugins.langs.go' },
  { import = 'me.plugins.langs.html' },
  { import = 'me.plugins.langs.javascript' },
  { import = 'me.plugins.langs.json' },
  { import = 'me.plugins.langs.jsonnet' },
  { import = 'me.plugins.langs.lua' },
  { import = 'me.plugins.langs.markdown' },
  { import = 'me.plugins.langs.python' },
  { import = 'me.plugins.langs.ruby' },
  { import = 'me.plugins.langs.shell' },
  { import = 'me.plugins.langs.terraform' },
  { import = 'me.plugins.langs.toml' },
  { import = 'me.plugins.langs.yaml' },
}
