#!/bin/zsh
# Display path in titlebar of terms.
# Automatic function called every time there is a path change (that I called,
# not within another script)
[[ -t 1 ]] || return 0
case $TERM in
    *xterm*|*rxvt*|(dt|k|E)term)
        print -Pn "\e]2;%~@$(hostname)\a"
    ;;
esac
