# Zsh user configuration file

# Ensure that we have a sane (not-empty) umask. This might happen if umask is
# not called in /etc/profile or if pam_umask hasn't had a chance yet
if [ ! $(( $(umask) + 0 )) -gt 0 ]; then
  # Nope, an empty umask this time around. Fix it with one that works well for
  # me:
  umask 022
fi

# Disable color and theme in dumb/basic terminals.
if [[ "$TERM" == 'dumb' || "$TERM" == "linux" ]]; then
  zstyle ':zsh' color 'no'
  zstyle ':zsh:prompt' theme 'off'
fi

# Hard coded path since we don't know what kind of environment we're in
local zshrc_snipplet
for zshrc_snipplet in $ZDOTDIR/conf/*.zsh ; do
        source $zshrc_snipplet
done

# And load local configuration overrides
[[ -r ~/.zshrc.local && ! -r $ZDOTDIR/local.zsh ]] && mv -v ~/.zshrc.local $ZDOTDIR/local.zsh
[[ -r $ZDOTDIR/local.zsh ]] && source $ZDOTDIR/local.zsh

# Stop tracing in zsh
if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    zprof
    zmodload -u zsh/zprof
    exec 2>&3 3>&-
fi
